name: 'tiktok_ads'
version: '0.4.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  tiktok_ads:
    +schema: tiktok_ads
    +materialized: table
vars:
  tiktok_ads:
    ad_group_report_hourly: "{{ ref('stg_tiktok_ads__ad_group_report_hourly') }}"
    ad_group_history: "{{ ref('stg_tiktok_ads__ad_group_history') }}"
    campaign_report_hourly: "{{ ref('stg_tiktok_ads__campaign_report_hourly') }}"
    campaign_history: "{{ ref('stg_tiktok_ads__campaign_history') }}"
    ad_report_hourly: "{{ ref('stg_tiktok_ads__ad_report_hourly') }}"
    ad_history: "{{ ref('stg_tiktok_ads__ad_history') }}"
    advertiser: "{{ ref('stg_tiktok_ads__advertiser') }}"
  tiktok_ads__ad_group_hourly_passthrough_metrics: []
  tiktok_ads__ad_hourly_passthrough_metrics: []
  tiktok_ads__campaign_hourly_passthrough_metrics: []
